Allow Bash to use OMP

diff --git a/dot_bashrc b/dot_bashrc
--- a/dot_bashrc
+++ b/dot_bashrc
@@ -14,17 +14,6 @@ if [[ -d "$NVM_DIR" ]] ; then
     if [[ -f "$HOME/.nvmrc" ]] ; then nvm use > /dev/null ; fi 
 fi
 
-
-# PS1
-GIT_PS1_SHOWDIRTYSTATE=1
-GIT_PS1_SHOWSTASHSTATE=1
-GIT_PS1_SHOWUNTRACKEDFILES=1
-GIT_PS1_SHOWUPSTREAM="verbose"
-GIT_PS1_SHOWCONFLICTSTATE="yes"
-GIT_PS1_SHOWCOLORHINTS=true
-
-PROMPT_COMMAND='PS1="\[\033[35m\]\t\[\033[m\] - \[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]`__git_ps1 " [%s]"`\n\`if [[ \$? = "0" ]]; then echo "\\[\\033[32m\\]"; else echo "\\[\\033[31m\\]"; fi\`\$ \[\033[m\]"'
-
 for file in $(find ~/.shrc.d -name '*.sh' -type f) ; do 
   source "$file" ;
 done
@@ -32,3 +21,19 @@ done
 for file in $(find ~/.shrc.d -name '*.bash' -type f) ; do 
   source "$file" ;
 done
+
+# Oh My Posh must be enabled after oh-my-zsh to ensure correct working
+if command oh-my-posh > /dev/null 2>&1 ; then
+    eval "$(oh-my-posh init zsh --config ~/.config/omp/config.toml)"
+else
+    echo "oh-my-posh not found"
+    # PS1
+    GIT_PS1_SHOWDIRTYSTATE=1
+    GIT_PS1_SHOWSTASHSTATE=1
+    GIT_PS1_SHOWUNTRACKEDFILES=1
+    GIT_PS1_SHOWUPSTREAM="verbose"
+    GIT_PS1_SHOWCONFLICTSTATE="yes"
+    GIT_PS1_SHOWCOLORHINTS=true
+
+    PROMPT_COMMAND='PS1="\[\033[35m\]\t\[\033[m\] - \[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]`__git_ps1 " [%s]"`\n\`if [[ \$? = "0" ]]; then echo "\\[\\033[32m\\]"; else echo "\\[\\033[31m\\]"; fi\`\$ \[\033[m\]"'
+fi
